namespace BiliUWP {
    runtimeclass FavouritesFolderViewItem {
        String Title{ get; };
        // NOTE: If an item has no cover, this property will return a placeholder cover url
        String CoverUrl{ get; };
        String Description{ get; };
        UInt64 UpMid{ get; };
        String UpName{ get; };
        String UpFaceUrl{ get; };
        UInt64 PlayCount{ get; };
        UInt64 DanmakuCount{ get; };
        UInt64 FavouriteCount{ get; };
        UInt32 ResItemType{ get; };
        UInt64 ResItemId{ get; };
    };
    runtimeclass FavouritesUserViewItem {
        String Title{ get; };
        // NOTE: If an item has no cover, this property will return a placeholder cover url
        String CoverUrl{ get; };
        String AttrStr{ get; };
        UInt64 MediaCount{ get; };
        UInt64 FolderId{ get; };
    };
    runtimeclass UserVideosViewItem {
        String Title{ get; };
        // NOTE: If an item has no cover, this property will return a placeholder cover url
        String CoverUrl{ get; };
        String PublishTimeStr{ get; };
        String Description{ get; };
        String PlayCountStr{ get; };
        UInt64 DanmakuCount{ get; };
        UInt64 AvId{ get; };
        Boolean IsUnionVideo{ get; };
    };
    runtimeclass UserAudiosViewItem {
        String Title{ get; };
        // NOTE: If an item has no cover, this property will return a placeholder cover url
        String CoverUrl{ get; };
        String PublishTimeStr{ get; };
        UInt64 PlayCount{ get; };
        UInt64 CommentsCount{ get; };
        UInt64 AuId{ get; };
    };
}
