namespace BiliUWP {
    [default_interface]
    runtimeclass StringToBitmapImageConverter : Windows.UI.Xaml.Data.IValueConverter {
        StringToBitmapImageConverter();
    };
    [default_interface]
    runtimeclass StringToUriConverter : Windows.UI.Xaml.Data.IValueConverter {
        StringToUriConverter();
    };

    [default_interface]
    runtimeclass UInt32ToSelectedIndexConverter : Windows.UI.Xaml.Data.IValueConverter {
        UInt32ToSelectedIndexConverter();
    }

    [default_interface]
    runtimeclass NumberScaleConverter : Windows.UI.Xaml.Data.IValueConverter {
        NumberScaleConverter();
    }
}
