namespace BiliUWP {
    // Should be inherited by pages
    interface IBiliResource {
        Boolean IsBiliResReady();
        // Main resource identifier; can be null
        String BiliResId{ get; };
        String BiliResUrl{ get; };
        // Alternative resource identifier; can be null
        String BiliResId2{ get; };
        String BiliResUrl2{ get; };
    };
}
