import "IBiliResource.idl";

namespace BiliUWP {
    struct FavouritesFolderPageNavParam {
        UInt64 folder_id;
    };

    [default_interface]
    runtimeclass FavouritesFolderPage : Windows.UI.Xaml.Controls.Page, IBiliResource {
        FavouritesFolderPage();
    }
}
