namespace BiliUWP {
    struct FavouritesUserPageNavParam {
        UInt64 uid;
    };

    [default_interface]
    runtimeclass FavouritesUserPage : Windows.UI.Xaml.Controls.Page {
        FavouritesUserPage();
    }
}
