namespace BiliUWP {
    runtimeclass FavouriteUserViewPage_ViewItem {
        String Title{ get; };
        // NOTE: If an item has no cover, this property will return a placeholder cover url
        String CoverUrl{ get; };
        String AttrStr{ get; };
        UInt64 MediaCount{ get; };
    };

    [default_interface]
    runtimeclass FavouriteUserViewPage_ViewItemSource :
        IObservableVector<IInspectable>, Windows.UI.Xaml.Data.ISupportIncrementalLoading
    {
        // Param: true => Loading; false => Loaded
        event Windows.Foundation.EventHandler<Boolean> LoadingStateChanged;
        void Reload();
        UInt32 TotalItemsCount{ get; };
    };

    struct FavouritesUserPageNavParam {
        UInt64 uid;
    };

    [default_interface]
    runtimeclass FavouritesUserPage : Windows.UI.Xaml.Controls.Page {
        FavouritesUserPage();

        FavouriteUserViewPage_ViewItemSource ViewItemSource{ get; };
    }
}
