namespace BiliUWP {
    enum LoginPageResult {
        Ok,
        UserCanceled
    };

    [default_interface]
    runtimeclass LoginPage : Windows.UI.Xaml.Controls.Page {
        LoginPage();

        // NOTE: For unrecoverable errors, an exception will be thrown
        // NOTE: The login operation is started once the page is added;
        //       awaiting RequestLogin can tell you when the login has
        //       completed. Cancelling the operation has no effect on
        //       the login process.
        Windows.Foundation.IAsyncOperation<LoginPageResult> RequestLogin(void);
    }
        
    // Private only
    enum QRCodePollResult {
        Success,
        Continue,
        Expired,
    };
}
