import "IBiliResource.idl";

namespace BiliUWP {
    enum MediaPlayPage_MediaType {
        Video,
        Audio,
    };
    // NOTE: sid is preferred if applicable (nid will be used only when sid is null)
    struct MediaPlayPageNavParam {
        MediaPlayPage_MediaType type;
        UInt64 nid;
        String sid;
    };

    [default_interface]
    runtimeclass MediaPlayPage : Windows.UI.Xaml.Controls.Page, IBiliResource {
        MediaPlayPage();

        Windows.UI.Xaml.Controls.MediaPlayerElement MediaPlayerElem{ get; };
    }
}
