import "IBiliResource.idl";
import "AppCfgModel.idl";
import "Controls/CustomMediaPlayerElement.idl";

namespace BiliUWP {
    runtimeclass MediaPlayPage_UpItem {
        String UpName{ get; };
        String UpFaceUrl{ get; };
        UInt64 UpMid{ get; };
    }
    runtimeclass MediaPlayPage_PartItem {
        UInt64 PartNo{ get; };
        String PartNoText{ get; };
        String PartName{ get; };
        UInt64 PartCid{ get; };
    }

    enum MediaPlayPage_MediaType {
        Video,
        Audio,
    };
    // NOTE: sid is preferred if applicable (nid will be used only when sid is null)
    struct MediaPlayPageNavParam {
        MediaPlayPage_MediaType type;
        UInt64 nid;
        String sid;
    };

    [default_interface]
    runtimeclass MediaPlayPage : Windows.UI.Xaml.Controls.Page, IBiliResource {
        MediaPlayPage();

        //Windows.UI.Xaml.Controls.MediaPlayerElement MediaPlayerElem{ get; };
        CustomMediaPlayerElement MediaPlayerElem{ get; };

        String MediaTitle{ get; };
        String MediaCoverImageUrl{ get; };
        String MediaDescription{ get; };
        String MediaPublishTimeStr{ get; };
        UInt64 MediaPlayCount{ get; };
        UInt64 MediaDanmakuCount{ get; };
        UInt64 MediaCommentsCount{ get; };
        IObservableVector<IInspectable> UpList{ get; };
        Boolean ShouldShowPartsList{ get; };
        IObservableVector<IInspectable> PartsList{ get; };

        AppCfgModel CfgModel{ get; };
    }
}
