import "AppCfgModel.idl";

namespace BiliUWP {
    [default_interface]
    runtimeclass SettingsPage : Windows.UI.Xaml.Controls.Page {
        SettingsPage();

        void UnloadObject(Windows.UI.Xaml.DependencyObject object);

        AppCfgModel CfgModel{ get; };
        Windows.UI.Xaml.DebugSettings AppDebugSettings{ get; };
    }
}
