import "IBiliResource.idl"; 

namespace BiliUWP {
    enum UserPage_TargetPart {
        PublishedVideos,
        Followers,
    };

    struct UserPageNavParam {
        UInt64 uid;
        UserPage_TargetPart target_part;
    };

    [default_interface]
    runtimeclass UserPage : Windows.UI.Xaml.Controls.Page, IBiliResource {
        UserPage();
    }
}
