import "AppCfgModel.idl";

namespace BiliUWP.Settings {
    [default_interface]
    runtimeclass DeveloperPage : Windows.UI.Xaml.Controls.Page {
        DeveloperPage();

        BiliUWP.AppCfgModel CfgModel{ get; };
        Windows.UI.Xaml.DebugSettings AppDebugSettings{ get; };
    };
}
