import "AppCfgModel.idl";

namespace BiliUWP.Settings {
    [default_interface]
    runtimeclass MiscPage : Windows.UI.Xaml.Controls.Page {
        MiscPage();

        BiliUWP.AppCfgModel CfgModel{ get; };
    };
}
