namespace BiliUWP {
    [default_interface]
    runtimeclass SimpleStateOverlay : Windows.UI.Xaml.Controls.UserControl {
        SimpleStateOverlay();

        void SwitchToHidden();
        void SwitchToLoading(String text);
        void SwitchToFailed(String text);
    }
}
