namespace BiliUWP {
    enum SimpleStateIndicatorLayoutType {
        Full,
        Inline,
    };

    [default_interface]
    runtimeclass SimpleStateIndicator : Windows.UI.Xaml.Controls.UserControl {
        SimpleStateIndicator();

        static Windows.UI.Xaml.DependencyProperty LayoutTypeProperty{ get; };
        SimpleStateIndicatorLayoutType LayoutType;

        void SwitchToHidden();
        void SwitchToLoading(String text);
        void SwitchToFailed(String text);
        void SwitchToDone(String text);
    }
}
